[package]
name = "eterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.6.0"
phf = { version = "0.11.2", features = ["macros"] }
spidev = "0.6.0"
